name: Daily Stock Alerts
on:
  schedule:
    - cron: '0 1 * * *'  # 1 AM UTC daily
  workflow_dispatch:  # Allow manual trigger
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Stock Check
        run: |
          echo "Triggering stock check..."
          response=$(curl -s -w "\n%{http_code}" -X POST https://web-production-59017.up.railway.app/admin/check \
            -H "Content-Type: application/json")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Stock check completed successfully"
          else
            echo "❌ Stock check failed with status $http_code"
            exit 1
          fi